name: neon
dependencies:
- alabaster=0.7.6=py27_0
- appnope=0.1.0=py27_0
- babel=2.1.1=py27_0
- backports_abc=0.4=py27_0
- bokeh=0.9.3=np19py27_0
- colorama=0.3.3=py27_0
- decorator=4.0.4=py27_0
- docutils=0.12=py27_0
- flask=0.10.1=py27_1
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.9=py27_0
- h5py=2.4.0=np19py27_0
- hdf5=1.8.14=0
- ipython=4.0.0=py27_1
- ipython_genutils=0.1.0=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- numpy=1.9.3=py27_0
- openssl=1.0.2d=0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pygments=2.0.2=py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_1
- readline=6.2=2
- requests=2.8.1=py27_0
- setuptools=18.5=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- ujson=1.33=py27_0
- werkzeug=0.11.2=py27_0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - astroid==1.4.1
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - configargparse==0.9.3
  - coverage==4.0.3
  - cython==0.23.4
  - flake8==2.4.1
  - ipython-genutils==0.1.0
  - lazy-object-proxy==1.2.1
  - logilab-common==1.1.0
  - mccabe==0.3.1
  - pep8==1.5.7
  - pillow==2.9.0
  - posix-ipc==1.0.0
  - py==1.4.31
  - pyflakes==0.8.1
  - pylint==1.4.4
  - pytest==2.7.2
  - pytest-cov==2.0.0
  - sphinx-rtd-theme==0.1.7
  - subprocess32==3.2.6
  - wrapt==1.10.5

